/* Introduces steps to build and test the fe-bookatop on dev environment */

pipeline {
    agent any

    stages {
        stage('Clean/Build') {
            steps {
                sh 'gradle clean build -x test'
            }
        }
        stage('Test') {
            steps {
                sh 'gradle test'
            }
        }
    }
}