/* Introduces steps to build and test the fe-bookatop on dev environment */

pipeline {
    agent any

    environment {
        SOUR_PATH = 'services'
        DEST_PATH = '/path/dev-env/fe-bookatop/releases/${BRANCH_NAME}'
    }

    stages {
        stage('Clean/Build/Test') {
            steps {
                sh 'ls -l'
            }
        }
        stage('Test') {
            steps {
                sh 'echo done'
            }
        }
    }
}