pipeline {
    agent any

    stages {
        stage('Clean and build') {
            steps {
                sh 'gradle clean build -x test'
            }
        }
        stage('Test') {
            steps {
                sh 'gradle test'
            }
        }
        stage('Deploy on dev env') {
            steps {
                sh "mkdir -p /path/dev-env/be-bookatop/releases/${env.BRANCH_NAME}"
                sh "cp services/auth/build/libs/auth-service.jar /path/dev-env/be-bookatop/releases/${env.BRANCH_NAME}/auth-service-${env.BUILD_NUMBER}.jar"
            }
        }
    }
}