pipeline {
    agent any

    options {
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '5', daysToKeepStr: '', numToKeepStr: '5')
    }

    stages {
        stage('Build on DEV') {
            steps {
                script {
                    String projectName = 'build-frontend-on-dev'
                    String jenkinsHome = '/var/lib/jenkins'
                    GString destRelease = "${jenkinsHome}/jobs/${projectName}/branches/${BRANCH_NAME}/builds/${BUILD_NUMBER}/release"

                    String file = 'build-frontend-on-dev.sh'
                    String script = libraryResource "com/bookatop/scripts/${file}"

                    writeFile(file: file, text: script)
                    sh "chmod +x ./${file}"
                    sh "./${file} ${destRelease}"
                }
            }
        }
    }
}