/* Introduces steps to build and test the be-bookatop on dev environment */

pipeline {
    agent any

    environment {
        BUILD_SERVICE_PATH = 'services'
        RELEASE_PATH = '/path/dev-env/be-bookatop/releases'
    }

    stages {
        stage('Clean/Build/Test') {
            steps {
                sh 'gradle clean build test'
            }
        }
        stage('Prepare release for dev environment') {
            steps {
                echo "Copy release:${BRANCH_NAME}:${BUILD_NUMBER} on branch on dev environment"

                script {
                    def services = ['auth']

                    list.each { item ->
                          sh '''
                             echo Fetch service ${item}
                          '''
                       }
                }

            }
        }
    }
}