/* Introduces steps to build and test the be-bookatop on dev environment */

pipeline {
    agent any

    environment {
        SOUR_PATH = 'services'
        DEST_PATH = '/path/dev-env/be-bookatop/releases'
    }

    stages {
        stage('Clean/Build/Test') {
            steps {
                sh 'gradle clean build test'
            }
        }
        stage('Prepare release for dev environment') {
            steps {
                echo "Copy release:${BRANCH_NAME}:${BUILD_NUMBER} on branch on dev environment"

                script {
                    def services = ['auth']

                    services.each { item ->
                          varSourceFile = "${SOUR_PATH}/${item}/build/libs/${item}-service.jar"
                          varDestFile = "${DEST_PATH}/${item}-service-${BUILD_NUMBER}.jar"
                          sh """
                            echo Fetch service ${item}
                            if ! [ -f ${varSourceFile} ]; then
                                exit 1
                            fi
                            echo Paths
                            echo ${varSourceFile}
                            echo ${varDestFile}
                          """
                    }
                }

            }
        }
    }
}