/* Introduces steps to build and test the be-bookatop on dev environment */

pipeline {
    agent any

    stages {
        stage('Clean/Build/Test') {
            steps {
                sh 'gradle clean build test'
            }
        }
        stage('Release') {
            steps {
                sh 'ls'
            }
        }
    }
}