load 'Parameters.groovy'

pipeline {
    agent any

    options {
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '5', daysToKeepStr: '', numToKeepStr: '5')
    }

    stages {
        stage('Build on DEV') {
            steps {
                script {
                    String jenkinsHome = '/var/lib/jenkins'

                    GString sourceRelease = "${jenkinsHome}/jobs/build-backend-on-dev/branches/${releaseBranch}/builds/${releaseNumber}/release/${releaseName}-service.jar"
                    GString destRelease = "/path/dev-env/be-bookatop/deploy/${releaseName}-service.jar"

                    String file = 'deploy-backend-on-dev.sh'
                    String script = libraryResource "com/bookatop/scripts/${file}"

                    writeFile(file: file, text: script)
                    sh "chmod +x ./${file}"
//                    sh "./${file} ${sourceRelease} ${destRelease} ${releaseName}"
                }
            }
        }
    }
}