properties([
        parameters([
                [
                        $class    : 'ChoiceParameter',
                        choiceType: 'PT_SINGLE_SELECT',
                        name      : 'releaseBranch',
                        script    : [
                                $class: 'ScriptlerScript',
                                scriptlerScriptId: 'Branches.groovy'
                        ]
                ],
                [
                        $class              : 'CascadeChoiceParameter',
                        choiceType          : 'PT_SINGLE_SELECT',
                        name                : 'releaseName',
                        referencedParameters : 'releaseBranch',
                        script    : [
                                $class: 'ScriptlerScript',
                                scriptlerScriptId: 'Branches.groovy',
                                parameters: [
                                        [name: 'releaseBranch', value: $releaseBranch]
                                ]
                        ]
                ],
                [
                        $class              : 'ChoiceParameter',
                        choiceType          : 'PT_SINGLE_SELECT',
                        name                : 'releaseNumber',
                        script    : [
                                $class: 'GroovyScript',
                                script: [classpath: [],
                                         script   : """
                                             return []
                                         """
                                ]
                        ]
                ]
        ])
])

pipeline {
    agent any

    options {
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '5', daysToKeepStr: '', numToKeepStr: '5')
    }

//    parameters {
//        choice(
//                name: 'releaseBranch',
//                choices: branches(),
//                description: 'Choose branch name*'
//        )
//        choice(
//                name: 'releaseName',
//                choices: releases(${releaseBranch}),
//                description: 'Choose release name*'
//        )
//        validatingString(
//                name: 'releaseNumber',
//                defaultValue: lastRelease(${releaseBranch}),
//                description: 'Put the build number*',
//                failedValidationMessage: 'Build number is invalid',
//                regex: /^[0-9]+$/
//        )
//    }

    stages {
        stage('Build on DEV') {
            steps {
                script {
                    String jenkinsHome = '/var/lib/jenkins'

                    GString sourceRelease = "${jenkinsHome}/jobs/build-backend-on-dev/branches/${releaseBranch}/builds/${releaseNumber}/release/${releaseName}-service.jar"
                    GString destRelease = "/path/dev-env/be-bookatop/deploy/${releaseName}-service.jar"

                    String file = 'deploy-backend-on-dev.sh'
                    String script = libraryResource "com/bookatop/scripts/${file}"

                    writeFile(file: file, text: script)
                    sh "chmod +x ./${file}"
//                    sh "./${file} ${sourceRelease} ${destRelease} ${releaseName}"
                }
            }
        }
    }
}