pipeline {
    agent any

    options {
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '5', daysToKeepStr: '', numToKeepStr: '5')
    }

    parameters {
        validatingString(
                name: 'releaseName',
                defaultValue: 'auth',
                description: 'Put the service name*',
                failedValidationMessage: 'Service name is empty',
                regex: /^.+$/
        )
    }

    stages {
        stage('Build on PROD') {
            steps {
                script {
                    String jenkinsHome = '/var/lib/jenkins'

                    GString sourceRelease = "/path/dev-env/be-bookatop/deploy/${releaseName}-service.jar"
                    GString destRelease = "/path/prod-env/be-bookatop/deploy/${releaseName}-service.jar"

                    String file = 'deploy-backend-on-prod.sh'
                    String script = libraryResource "com/bookatop/scripts/${file}"

                    writeFile(file: file, text: script)
                    sh "chmod +x ./${file}"
                    sh "./${file} ${sourceRelease} ${destRelease}"
                }
            }
        }
    }

}