pipeline {
    agent any

    options {
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '5', daysToKeepStr: '', numToKeepStr: '5')
    }

    tools {
        jdk 'openjdk17'
    }

    stages {
        stage('Build on DEV') {
            steps {
                script {
                    String environment = 'dev'
                    String projectName = 'build-backend-on-dev'
                    String jenkinsHome = '/var/lib/jenkins'

                    String file = 'build-backend-on-dev.sh'
                    String script = libraryResource "com/bookatop/scripts/${file}"

                    writeFile(file: file, text: script)
                    sh "chmod +x ./${file}"

                    sh "./${file} ${jenkinsHome} ${environment} ${projectName} ${BRANCH_NAME} ${BUILD_NUMBER}"
                }
            }
        }
    }
}