pipeline {
    agent any

    options {
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '5', daysToKeepStr: '', numToKeepStr: '5')
    }

    stages {
        stage('Deploy on PROD') {
            steps {
                script {
                    String jenkinsHome = '/var/lib/jenkins'

                    String sourceRelease = "/path/dev-env/fe-bookatop/deploy"
                    String destRelease = '/path/prod-env/fe-bookatop/deploy'

                    String file = 'deploy-frontend-on-prod.sh'
                    String script = libraryResource "com/bookatop/scripts/${file}"

                    writeFile(file: file, text: script)
                    sh "chmod +x ./${file}"

                    sh "./${file} ${sourceRelease} ${destRelease}"
                }
            }
        }
    }
}